### ISSUE TITLE
NEW MARKLET???

### ISSUE THREAD

**Issue by Karichain** [2emk7/2emk7.github.io#4]
SOO i was wondering if you could make a bookmarklet for Aleks topics and make like a gui or something plzzzz because doing aleks is so annoying. https://www.aleks.com/

**Comment by zpenguin360** [comment]
can u add one for a proxy pls
btw u can find the source code on replit
if possible can it be rammerhead or any uv proxy if so thanks

**Comment by Karichain** [comment]
Kid this my issue i need aleks hack boy math teacher dodo

**Comment by 2emk7** [comment]
i dont use that site so i am unable to help you with that

**Comment by zpenguin360** [comment]
@2emk7 ok ill use another repository, sorry if I wasted your time

**Comment by zpenguin360** [comment]
also @Karichain i wasnt talking to you
